lobal_defs {
    log_level           DEBUG                # Set to INFO or WARN for production
    log_file            /var/log/dpvs.log
    <init> log_async_mode    on
    <init> kni               off              # Disable KNI if you don't use Linux kernel stack
    lldp                off
}

netif_defs {
    <init> pktpool_size     16384
    <init> pktpool_cache    64

    <init> device dpdk0 {
        rx {
            queue_number        1
            descriptor_number   256
            rss                 none
        }
        tx {
            queue_number        1
            descriptor_number   256
        }
        kni_name                dpdk0.kni
    }
}

worker_defs {
    <init> worker cpu0 {
        type    master
        cpu_id  0
    }

    <init> worker cpu1 {
        type    slave
        cpu_id  1
        port    dpdk0 {
            rx_queue_ids     0
            tx_queue_ids     0
        }
    }
}

timer_defs {
    schedule_interval    2000                 # Lower frequency timer, good for performance
}

neigh_defs {
    <init> unres_queue_length  16
    timeout                    20
}

ipset_defs {
    <init> ipset_hash_pool_size 2048
}

ipv4_defs {
    forwarding                 on              # Enable IPv4 forwarding
    <init> default_ttl         64
    fragment {
        <init> bucket_number   32
        <init> bucket_entries  4
        <init> max_entries     128
        <init> ttl             1
    }
}

ipv6_defs {
    forwarding                 on              # Enable IPv6 forwarding
    <init> default_hop_limit   64
    fragment {
        <init> bucket_number   32
        <init> bucket_entries  4
        <init> max_entries     128
        <init> ttl             1
    }
}

ctrl_defs {
    lcore_msg {
        <init> ring_size                256
        sync_msg_timeout_us             20000
        priority_level                  low
    }
}

ipvs_defs {
    conn {
        <init> conn_pool_size       8192
        <init> conn_pool_cache      64
        conn_init_timeout           2
    }

    udp {
        uoa_mode        opp
        uoa_max_trail   1
        timeout {
            oneway      15
            normal      30
            last        3
        }
    }

    tcp {
        timeout {
            none        2
            established 30
            syn_sent    3
            syn_recv    10
            fin_wait    3
            time_wait   3
            close       2
            close_wait  3
            last_ack    3
            listen      30
            synack      10
            last        2
        }
        synproxy {
            synack_options {
                mss             1452
                ttl             63
                sack
            }
            close_client_window
            rs_syn_max_retry    1
            ack_storm_thresh    3
            max_ack_saved       1
            conn_reuse_state {
                close
                time_wait
           }
        }
    }

    icmp {
        timeout {
            echo_request    5
            echo_reply      5
            dest_unreach    5
            time_exceeded   5
        }
    }

    icmpv6 {
        timeout {
            echo_request    5
            echo_reply      5
            dest_unreach    5
            time_exceeded   5
            packet_too_big  5
        }
    }
}

sa_pool {
    <init> pool_hash_size  4
    <init> flow_enable     off
}

