# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fuzz/mbuf_mutator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fuzz/mbuf_mutator.proto',
  package='dpvs',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x66uzz/mbuf_mutator.proto\x12\x04\x64pvs\"\xc5\x01\n\x0bMbufMutator\x12\x0f\n\x07pkt_len\x18\x01 \x01(\r\x12\x10\n\x08\x64\x61ta_len\x18\x02 \x01(\r\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x0f\n\x07nb_segs\x18\x04 \x01(\r\x12\x10\n\x08ol_flags\x18\x05 \x01(\r\x12\x12\n\neth_header\x18\x06 \x01(\x0c\x12\x10\n\x08vlan_tci\x18\x07 \x01(\r\x12\x11\n\tip_header\x18\x08 \x01(\x0c\x12\x18\n\x10transport_header\x18\t \x01(\x0c\x12\x0f\n\x07payload\x18\n \x01(\x0c'
)




_MBUFMUTATOR = _descriptor.Descriptor(
  name='MbufMutator',
  full_name='dpvs.MbufMutator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pkt_len', full_name='dpvs.MbufMutator.pkt_len', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_len', full_name='dpvs.MbufMutator.data_len', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='dpvs.MbufMutator.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nb_segs', full_name='dpvs.MbufMutator.nb_segs', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ol_flags', full_name='dpvs.MbufMutator.ol_flags', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eth_header', full_name='dpvs.MbufMutator.eth_header', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vlan_tci', full_name='dpvs.MbufMutator.vlan_tci', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_header', full_name='dpvs.MbufMutator.ip_header', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transport_header', full_name='dpvs.MbufMutator.transport_header', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='dpvs.MbufMutator.payload', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=231,
)

DESCRIPTOR.message_types_by_name['MbufMutator'] = _MBUFMUTATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MbufMutator = _reflection.GeneratedProtocolMessageType('MbufMutator', (_message.Message,), {
  'DESCRIPTOR' : _MBUFMUTATOR,
  '__module__' : 'fuzz.mbuf_mutator_pb2'
  # @@protoc_insertion_point(class_scope:dpvs.MbufMutator)
  })
_sym_db.RegisterMessage(MbufMutator)


# @@protoc_insertion_point(module_scope)
